#!/bin/bash
set -e

python_deps()
{
    ER=$(pip --version | awk '{print $2}')
    MAJOR=$(echo $VER | cut -f1 -d.)
    MINOR=$(echo $VER | cut -f2 -d.)
    if [ "${MAJOR:-0}" -lt 2 ] && [ "${MINOR:-0}" -lt 5 ]
    then
        echo "[ERROR] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
        echo "[ERROR] !! pip 1.5 or newer is required !!" 1>&2
        echo "[ERROR] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
        exit 1
    fi

    if [ -e dist ]; then
        rm -rf dist
    fi

    pip install -t dist -r dist-requirements.txt
    pip install --no-deps -t dist websockify
    cp dist-requirements.txt dist
}

cd $(dirname $0)/..

python_deps

if [ -e build ]; then
    rm -rf build
fi
